name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


env:
  DOCKER_IMAGE: medical-logistics-api

jobs:
  # Job 1: Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn clean test

      - name: Generate test report
        if: always()
        run: mvn surefire-report:report

  # Job 2: Build Docker image (only if tests pass)
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .

      - name: Save Docker image
        run: |
          docker save ${{ env.DOCKER_IMAGE }}:${{ github.sha }} > image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar